### ISSUE TITLE
The format of training_samples and validation samples

### ISSUE THREAD

**Issue by baoqiangma96** [MungoMeng/Survival-DeepMSS#1]
It is unclear what the training_samples and validation samples files should be prepared. It would be nice to show it for implement your codes

**Comment by MungoMeng** [comment]
Hi Baoqiang, thanks for your question!

The 'training_samples' or 'valid_samples' should be pointed to a '.npy' file. Within the file is a list containing the file names of training/validation samples. E.g., ['Patient_1.npz', 'Patient_14npz', 'Patient_18.npz', 'Patient_22.npz']. All training/validation samples should be placed in the path 'data_dir'.

Please take a look at the code in the 'datagenerators.py'. You can define your own data loading functions for your specific data format.

**Comment by baoqiangma96** [comment]
Thanks for the reply, it 's very nice work !

I did look at your datagenerators.py. Now I understand better ! Is it each 'Patient_1.npz' should include a dict {'CT': numpy, 'PET': numpy, 'Seg_tumor' : numpy ,   'Seg_Node': numpy,   'Time:' 123 , 'Event:' 0 } ?

**Comment by MungoMeng** [comment]
Yes, you get it!

**Comment by baoqiangma96** [comment]
Thanks !
