### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sunyyyl0106** [MungoMeng/Survival-DeepMSS#2]
I noticed that the project does not include an environment file (e.g., requirements.txt, environment.yml), which would specify the dependencies required to set up the environment. Could you kindly provide a list of dependencies or the preferred environment setup for running the project?

**Comment by MungoMeng** [comment]
Hi, our experimental environment is Pytorch==1.13 with a 12GB NVIDIA Titan V GPU.
imgaug was used for data augmentation and lifelines was used for calculating C-index.
