### ISSUE TITLE
PET images processing

### ISSUE THREAD

**Issue by sunyyyl0106** [MungoMeng/Survival-DeepMSS#3]
When processing the PET images, they are not mapped into range [−1, 1] right?

**Comment by MungoMeng** [comment]
Thanks for your interests in our work!
Yes, we processed PET images using Z-score normalization after converting them into SUV maps.
I think you can also try to map into [-1, 1] and this would not cause significant differences.

**Comment by sunyyyl0106** [comment]
Thank you very much!
For the hecktor dataset, how do you obtain injected dose to calculate the SUV?

**Comment by MungoMeng** [comment]
Please see: https://hecktor.grand-challenge.org/Data/
The provided PET images in HECKTOR challenge have been preprocessed as SUV maps.
